#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[248] =
    {   0,
        0,    0,   79,   77,   74,   76,   75,   77,   77,   73,
       72,   70,   77,    3,    3,    3,   69,   71,   68,   38,
       41,   68,   50,   68,   68,   68,   68,   39,   51,   40,
       68,   49,   33,   68,   68,   68,   68,    0,    4,    0,
        2,   68,   68,   68,   68,    3,   68,   68,   68,   68,
       68,   68,   43,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   44,   68,   45,   68,   68,   35,   68,   42,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       66,   68,   68,   68,   68,   68,   68,   48,   68,   68,
       46,   47,   17,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,    8,   68,   29,   35,   68,   68,
       68,   57,   68,   68,   68,   68,   68,   68,   68,   23,
       68,   36,   68,   68,   68,   68,   68,   68,   68,   34,
       68,   68,   22,   68,   68,   68,   68,   68,   68,   68,
        7,   68,   68,   58,   37,   52,   68,   53,   68,   68,
       68,   55,   68,   68,   20,   68,   68,   68,   16,   10,
       68,   68,   68,   68,   54,    6,   68,   13,    9,   68,
       68,   68,   68,   68,   68,   68,   30,   68,   68,   12,
       68,   21,   68,   32,   68,   68,   25,   27,   18,   68,
       68,   26,   28,   68,   68,   68,   68,   68,   68,   68,

       68,   15,   68,   68,   24,    5,   31,   68,   11,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,    1,
       68,   68,   68,   19,   68,   63,   68,   62,   68,   61,
       68,   56,   68,   68,   68,   59,   60,   68,   68,   65,
       14,   64,   68,   68,   68,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    8,    1,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   12,   13,
       14,   12,   12,   12,   12,   12,   12,    1,    1,    1,
       15,   16,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       26,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        1,    1,    1,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   26,   52,   53,   54,   55,
       56,   57,   26,   58,   59,   60,   61,   62,   63,   64,
       65,   66,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   26,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   26,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   26,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    3,    3,    3,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[253] =
    {   0,
        0,    0,   91, 2563, 2563, 2563, 2563,   85,   86, 2563,
     2563, 2563,   55,   60,   65,   70, 2563, 2563,  109,  153,
      198,   79,  106,  238,  165,  151,  280,  152,  195,  327,
      228,  367,  410,  269,  450,  496,  167,   83, 2563,   83,
     2563,  208,  279,   83,  129,  326,  349,  414,  440,  387,
      286,  439,  347,  467,  526,  365,  450,  524,  569,  526,
      523,  412,  569,  571,  587,  614,  615,  638,  631,  648,
      681,  665,  721,  720,  666,  729,  528,  771,  772,  767,
      654,  768,  809,  820,  141,  683,  820,  790,  869,  875,
      847,  868,  877,  882,  906,  953,  924,  925,  961,  980,

      985, 1003, 1008, 1022, 1027, 1045, 1059, 1081, 1094, 1091,
     1094, 1113, 1108, 1126, 1139, 1141,  890, 1178, 1164,  954,
     1178, 1200, 1207, 1216, 1225, 1240, 1256, 1268, 1277, 1289,
     1298, 1282, 1317, 1323, 1345, 1370, 1381, 1394, 1407, 1266,
     1396, 1409, 1413, 1426, 1437, 1441, 1464, 1466, 1477, 1468,
     1491, 1499, 1544, 1520, 1521, 1549, 1577, 1566, 1594, 1597,
     1608, 1614, 1635, 1655, 1656, 1657, 1694, 1704, 1712, 1717,
     1727, 1716, 1738, 1752, 1763, 1775, 1740, 1772, 1783, 1782,
     1815, 1818, 1829, 1834, 1848, 1866, 1864, 1880, 1894, 1896,
     1910, 1924, 1926, 1973, 1959, 1971, 1970, 2026, 2031, 2041,

     2046, 2045, 2051, 2062, 2067, 2081, 2086, 2108, 2109, 2136,
     2144, 2141, 1514, 2162, 2207, 2212, 2217, 2223, 2148, 1800,
     2221, 2266, 2271, 2267, 2270, 2273, 2320, 2325, 2330, 2335,
     2332, 2344, 2389, 2394, 2389, 2400, 2412, 2337, 2437, 2445,
     2442, 2444, 2470, 2491, 2497, 2510, 2563, 2552, 2555,   82,
     2557, 2559
    } ;

static const flex_int16_t yy_def[253] =
    {   0,
      247,    1,  247,  247,  247,  247,  247,  248,  249,  247,
      247,  247,  250,  251,  251,  251,  247,  247,  251,  251,
      251,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   27,   20,  248,  247,  249,
      247,   20,   20,  252,  251,  251,  251,  251,  251,  251,
       27,   27,   27,   27,  251,   20,   27,   27,   27,   27,
       27,   20,   20,   20,   20,   20,   20,  251,   20,   20,
       20,   20,   20,   20,   20,   20,   27,   27,   73,   27,
       27,   27,   27,   27,   30,   20,   20,   20,  252,  252,
       20,   20,   20,   30,   30,  252,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,  251,  251,   30,
       30,   30,   20,   20,   20,   20,   27,   27,   27,   27,
       30,   30,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   30,   30,   30,   30,  252,  252,  252,  252,   27,
       27,   27,   27,   27,   27,   27,   30,   30,   20,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,  251,  251,  251,  251,
      251,   30,  252,  252,  252,  252,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,  252,   27,   27,   27,  252,  252,  252,

      252,   27,   30,   30,   30,   30,   30,   30,   30,  252,
      252,   30,   20,   20,  252,  252,  252,  252,   20,   20,
       20,  252,  252,   20,   30,   30,  252,  252,  252,  252,
       20,   20,  252,  252,   27,  252,  252,   30,  252,  252,
       30,   30,  252,  252,  252,  252,    0,  247,  247,  247,
      247,  247
    } ;

static const flex_int16_t yy_nxt[2630] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,    4,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   26,   28,   29,   30,   31,
       26,   32,   33,   34,   35,   36,   26,   37,   26,   26,
       26,    4,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   26,   32,   33,   34,   35,
       36,   26,   37,   26,   26,   26,   42,   42,   42,   44,
       45,   46,   46,   46,   44,   45,   46,   46,   46,   44,
       45,   46,   46,   46,   43,   41,   48,   39,   41,   39,
      247,   49,   44,   44,   89,   89,   89,  247,  247,   58,

       47,   44,  247,   59,  247,  247,   44,   47,  247,  247,
      247,   44,   48,  247,  247,  247,  247,   49,   44,   45,
       50,   50,   50,  247,   44,   58,   47,   47,   51,   59,
       47,  247,   47,  247,   47,  247,   52,  247,   44,   44,
       50,   50,   50,  247,   60,  247,  247,  247,  247,  247,
       44,  247,  247,   47,   51,  247,   47,  247,   47,   47,
      247,   52,   44,   45,   50,   50,   50,   47,  247,   60,
       44,  130,   47,   47,   53,   47,   47,   54,  247,   47,
       47,   55,  247,  247,   47,  247,   47,  247,   88,   47,
      247,   47,   47,   47,   44,   47,  130,   67,   47,   47,

       53,   47,   47,   54,   47,   47,   55,   44,   45,   50,
       50,   50,   47,  247,   88,   47,   47,   47,   47,   47,
       47,   56,   67,   47,  247,   71,  247,  247,   57,   47,
      247,  247,   47,  247,  247,  247,   47,  247,  247,   44,
      247,  247,   47,  247,   75,   47,  247,   56,   47,   47,
       71,  247,   47,   57,   61,   47,   47,   62,   47,   63,
      247,   47,   64,  247,  247,  247,   47,  247,  247,  247,
       75,   65,  247,   66,  247,   47,  247,  247,   47,  247,
       61,   47,  247,   62,  247,   63,   81,  247,   64,  247,
       47,   47,  247,   82,  247,  247,   65,   47,   66,   68,

       47,   47,  247,   47,   47,   93,  247,   47,   47,   69,
      247,  247,   81,  247,  247,   47,   47,  247,   70,   82,
      247,  247,   47,  247,   47,   68,   47,   47,  247,   47,
       47,   93,   47,   47,   69,   44,   45,   46,   46,   46,
       47,  247,  247,   70,   72,  247,  247,  247,   47,   47,
      247,   47,  247,   73,  247,   47,  247,   74,   44,   45,
       50,   50,   50,  247,  247,  247,   47,   44,  247,  247,
       72,  247,  247,  247,   47,  247,   47,   47,   73,  247,
       47,  247,   74,   76,  247,   47,   47,  247,   47,   47,
       44,   47,   47,   97,  247,   47,   44,   45,   50,   50,

       50,   47,  247,  247,   77,  247,  247,  247,  247,   76,
       47,  247,   47,  247,   47,   47,  247,   47,   97,  247,
       47,  247,  247,   44,   45,   50,   50,   50,   44,   77,
       78,   47,  247,   47,   47,  247,  104,  247,   79,  247,
       47,  247,  247,  247,  247,   80,  247,   91,  247,   44,
       45,   50,   50,   50,  247,   44,   78,   47,   47,   47,
       47,  247,  104,   79,  247,   47,   94,  247,   47,   47,
       80,   47,   91,   92,   47,  247,  247,   47,   47,   98,
      247,   44,   83,  247,   47,  247,   47,  247,   47,   84,
      247,   94,  247,   47,  247,   47,   47,   47,   92,  247,

       47,   95,   47,   47,   98,   47,  247,   83,  247,  247,
      247,  247,   47,   47,   84,   47,  247,  247,   85,  247,
      247,   47,  247,  247,  247,   86,   95,  247,  247,   87,
       47,  247,  247,  247,   47,   44,   45,   50,   50,   50,
      247,   47,   47,   47,   85,   47,  102,  120,  247,  247,
       86,   99,   47,   47,   87,   47,  103,   47,  247,   47,
      247,   47,   47,  247,   47,  247,   47,   96,   47,   47,
      247,   47,  102,  120,  247,  247,   99,   47,   47,  247,
       47,  103,   47,  247,  247,  247,   47,   47,   47,   47,
       47,   47,   47,   47,  247,   47,  247,   47,   47,   47,

      247,  100,  101,  247,  247,  105,  247,   47,   47,  247,
      247,   47,  247,  247,   47,   47,   47,  247,   47,   47,
      247,   47,   47,   47,   47,  247,  100,  101,  247,  247,
      105,  247,   47,  247,   47,   47,   47,   47,   47,   47,
       47,  106,   47,   47,  247,  247,  107,   44,   45,  108,
      108,  108,   47,  247,  247,  109,  247,  247,  247,   47,
      247,   47,   47,  247,   47,   47,  106,   47,   47,   47,
      247,  107,   47,   47,  247,  247,   47,  247,   47,   44,
      247,  109,  247,   47,   47,  247,   47,   47,  247,   47,
       47,  247,   47,   47,  118,   47,  247,  112,   47,   47,

      247,   47,   47,  110,   47,   47,  247,  131,   47,   47,
      247,  132,   47,   47,  111,   47,   47,   47,   47,  118,
      247,  247,  112,  247,  247,  247,  247,  247,   47,  110,
       47,   47,  247,  131,   47,  247,  132,  247,  247,  111,
      113,   47,  114,  115,   47,   47,  247,  247,   47,   47,
       47,  247,  247,   47,  247,  117,  116,   47,  247,  247,
      247,  247,  247,  119,  247,  247,  113,   47,  114,  115,
       47,   47,  247,   47,   47,  247,   47,  247,  247,   47,
      117,  116,   47,  247,  247,  247,   47,   47,  119,  121,
       47,  123,  247,   47,  124,  247,   47,   47,  247,  247,

       47,  126,  122,  247,  247,   47,   47,  125,  127,   47,
      247,   47,   47,   47,   47,  121,   47,  123,   47,   47,
      124,   47,   47,  247,  247,   47,  126,  122,   47,  128,
       47,   47,  125,  127,   47,  247,  247,   47,   47,   47,
       47,   47,  247,   47,   47,  247,  247,   47,   47,   47,
      247,  129,  133,  247,   47,  128,  247,  247,   47,  247,
      247,  247,  247,   47,  247,   47,  247,   47,   47,  247,
       47,   47,   47,   47,   47,   47,  129,  133,   44,   44,
       89,   89,   89,   47,   44,   44,   89,   89,   89,   47,
      247,  247,   47,  247,   47,  247,   47,   47,   47,   47,

       47,   47,  247,  247,  247,   47,  247,  247,   47,   47,
       44,  247,  134,  247,  247,   47,   44,  247,   47,  158,
      247,   47,  135,   47,   47,   47,  247,   47,   47,  247,
       47,  247,   47,   47,  247,   47,   47,  134,  247,  247,
      247,   47,   47,  247,  158,  247,  247,  247,  135,   47,
       47,   47,  247,   47,  140,   47,  247,   47,  247,  141,
      247,   47,   44,   44,   89,   89,   89,   47,   47,  136,
      137,  247,  138,   47,  247,   47,   47,  139,   47,  140,
       47,  142,  247,   47,  141,  247,  247,   47,  247,  247,
      247,   47,   47,  247,   44,  136,  137,   47,  138,   47,

      143,  247,   47,  139,   47,  247,   47,  142,   47,  247,
       47,  144,   47,  247,  247,   47,   47,   47,  247,  247,
       47,  145,  247,   47,  247,   47,  143,  247,   47,   47,
      247,   47,  247,   47,   47,   47,  144,  247,   47,   47,
       47,  247,  146,  247,   47,  247,   47,  145,   47,  247,
      247,   47,   47,   47,   47,  147,  247,   47,   47,   47,
      247,  247,   47,   47,  247,   47,  247,  146,  247,  247,
       47,   47,  148,   47,  247,   47,   47,   47,   47,  247,
      147,  247,   47,  247,  247,   47,  247,  247,   47,   47,
       44,   45,  108,  108,  108,  247,   47,  148,  247,  247,

       47,  247,   47,   44,   45,   50,   50,   50,   47,  247,
       47,   47,  247,  247,   47,  150,  247,   47,  247,  247,
       47,  151,   44,  247,   47,  247,  247,  152,  149,   47,
       47,  247,  153,  247,   47,   44,   47,   47,  247,   47,
      247,  150,   47,   47,  247,   47,  151,   47,  247,   47,
      154,  247,  152,  149,   47,   47,   47,  247,  153,  155,
       47,   47,   47,   47,   47,   47,  247,   47,   47,   47,
      247,  156,  247,   47,  157,  247,  154,  247,  247,   47,
      247,  247,  247,   47,  155,  247,   47,  160,   47,   47,
      247,   47,   47,   47,   47,   47,  156,   47,  159,  157,

      247,  247,   47,  247,   47,  247,  247,   47,  161,   47,
      247,  247,  247,  160,  247,  247,   47,   47,   47,  247,
      247,   47,  247,   47,  159,  247,   47,   47,   47,   47,
       47,  162,   47,  161,  247,   47,  247,   47,  247,  247,
       47,   47,  247,   47,   47,  247,   47,  247,  163,   47,
      247,   47,  247,   47,   47,   47,  165,  162,  164,  247,
       47,   47,  247,   47,   47,  247,   47,  247,   47,   47,
      247,  247,   47,  163,  247,   47,  166,   47,   47,  247,
       47,  247,  165,  164,   47,  177,  247,   47,  167,   47,
       47,  247,   47,   47,  247,   47,   47,  168,   47,   47,

      247,   47,  166,   47,   47,   47,   47,  247,   47,   47,
       47,  177,  170,   47,  167,   47,  247,   47,   47,   47,
       47,   47,   47,  168,   47,   47,   47,   47,  247,   47,
       47,  247,  169,   47,   47,  247,   47,  170,  247,   47,
       47,  171,   47,   47,  247,   47,  247,   47,   47,   47,
      247,   47,  247,   47,  247,  247,  247,  169,  247,  247,
       47,  247,   47,  172,  247,  247,   47,  171,   47,  247,
      247,   47,   47,  247,   47,   47,  247,  247,   47,   44,
       44,   89,   89,   89,  247,  247,  247,  247,   47,  172,
       44,   44,   89,   89,   89,  247,   47,  247,  247,  247,

       47,  247,  173,   44,   44,   89,   89,   89,  174,  247,
      247,   44,  247,  247,  175,   47,   44,   44,   89,   89,
       89,  247,   44,  247,  247,   47,  247,  173,   47,  247,
      247,  179,   47,  174,   47,   44,  176,  247,   47,  247,
      175,   47,   47,  178,  247,   47,  247,   47,   44,  247,
       47,   47,  247,  247,   47,   47,   47,  179,   47,   47,
       47,  176,  247,   47,   47,  247,   47,   47,  178,  247,
       47,   47,   47,  247,  247,   47,   47,  247,  247,   47,
       47,   47,   47,   47,  247,  247,   47,   47,  247,   47,
      180,   47,   47,  247,   47,   47,   47,  182,   47,  247,

       47,  181,  247,  247,   47,   47,   47,   47,  247,   47,
       47,  247,  247,   47,  247,  180,  247,   47,   47,   47,
       47,   47,  182,  247,   47,  247,  183,  181,   47,   47,
       47,   47,  247,  247,  247,   47,   47,   47,  225,   47,
       47,  247,   47,  247,   47,   47,  247,  186,  247,   47,
       47,  183,  247,   47,   47,  247,  247,  247,   47,   47,
      247,   47,   47,   47,  225,   47,   47,   47,   47,  247,
      247,  247,  186,   47,   47,   47,  184,  185,   47,  247,
      187,  247,   47,   47,   47,   47,  247,   47,  247,   47,
      247,  247,  247,  247,   47,   47,   47,  247,   47,  247,

      189,  184,  185,   47,   47,  187,   47,   47,  247,  188,
      247,   47,   47,   47,  247,   47,   47,  247,  247,  247,
       47,  247,   47,   47,  247,  189,   47,   47,  247,   47,
      247,   47,   47,   47,  188,   47,  247,   47,  247,   47,
       47,  247,   47,   47,  190,  247,   47,  191,   47,  247,
      247,   47,   47,   47,   47,  247,  247,   47,  247,   47,
       47,  247,   47,  247,   47,  247,  192,  247,   47,  190,
      247,   47,  191,   47,   47,   47,   47,   47,  247,  247,
       47,  247,  247,  247,   47,   47,   47,  193,  247,   47,
      247,  192,  247,   47,   47,   47,  247,  247,   47,  247,

       47,   47,   47,   44,   45,   50,   50,   50,  247,   47,
       47,   47,  193,   44,   45,   50,   50,   50,   47,   47,
       47,   44,   45,   50,   50,   50,   44,   45,   50,   50,
       50,  247,  247,   47,  247,  194,   44,   45,   50,   50,
       50,  247,   47,  196,  247,   44,  197,   44,   44,   89,
       89,   89,  195,   44,  247,  198,  247,   47,   44,   47,
      247,   44,   44,   89,   89,   89,   47,   47,   44,  196,
       47,  197,   44,   44,   89,   89,   89,  195,  247,   44,
      247,  198,  199,   47,   44,   44,   89,   89,   89,   47,
      247,   47,  202,   44,  247,   47,  247,  200,   47,   47,

       47,  247,   47,  247,   44,  201,  247,  199,   47,   47,
      247,  247,   47,   47,  247,   47,   44,  203,  202,  247,
      247,   47,  200,   47,   47,   47,   47,   47,   47,  247,
      201,  204,   47,   47,   47,   47,  247,   47,   47,  247,
      247,   47,  203,  247,   47,   47,   47,   47,   47,  247,
       47,   47,  247,   47,  247,   47,  247,  204,   47,   47,
       47,   47,  247,  205,   47,   47,   47,  247,  247,   47,
       47,  247,   47,   47,  206,  247,  247,   47,   47,  247,
       47,   47,  247,   47,   47,   47,  207,  247,  205,   47,
       47,   47,   47,  247,   47,  247,   47,   47,  247,  206,

      247,  247,  247,   47,  247,  247,   47,   47,  247,   47,
       47,   47,  207,   47,  247,   47,  208,   47,  247,   47,
       47,   47,   47,   47,   47,  247,   47,   47,  247,  247,
      247,   47,  247,  247,  247,   47,  209,   47,  247,   47,
       47,   47,  208,   47,  247,   47,  247,   47,  247,   47,
       47,   47,   47,   47,   47,  247,   47,  247,  247,  247,
      247,  209,  247,  247,  247,   47,  247,   47,  247,   47,
      247,  247,  247,  247,  247,   47,  247,   47,   47,   47,
      247,   47,   44,   44,   89,   89,   89,  247,  212,   47,
       47,  210,  247,  247,  211,  247,  247,   47,  247,   47,

       47,  247,  214,  247,   47,  213,  247,  247,   47,   47,
      247,  247,  247,  212,   44,   47,   47,  210,  247,  247,
      211,  247,   47,  247,   47,   47,  247,  214,  247,  247,
      213,  247,  247,   47,   47,   44,   44,   89,   89,   89,
       44,   44,   89,   89,   89,  215,  247,  247,  247,  216,
       44,   44,   89,   89,   89,   44,   44,   89,   89,   89,
      217,  247,  247,  247,   47,  218,  247,   44,   47,  247,
      247,  215,   44,  247,   47,  216,  247,   47,  247,   47,
      247,  219,   44,   47,   47,  247,  217,   44,   47,  220,
       47,  218,   47,   47,   47,  247,  247,   47,   47,   47,

      247,  247,   47,   47,  247,   47,  219,   47,   47,  247,
       47,   47,   47,   47,  220,  247,   47,   47,   47,  247,
      247,  247,   47,  247,   47,   47,   47,  247,  247,   47,
      247,  247,   47,  247,   47,   47,   47,   47,   47,   47,
      221,   47,  247,  247,  247,   44,   44,   89,   89,   89,
      247,   47,   47,   44,   44,   89,   89,   89,   47,   47,
       47,  247,  247,   47,   47,  221,  222,   47,  223,   47,
      247,   47,   47,  247,  247,  224,   47,   44,  226,  247,
      231,  247,  247,   47,   47,   44,   47,  247,  247,  247,
       47,  222,   47,  247,  223,   47,   47,  247,   47,  247,

      224,   47,  247,  247,  226,  231,  247,  247,  247,   47,
      247,  247,   47,  247,  247,   47,   44,   44,   89,   89,
       89,   44,   44,   89,   89,   89,   44,   44,   89,   89,
       89,  227,   44,   44,   89,   89,   89,  247,  228,  247,
      247,  229,   47,  230,  247,   47,  247,  247,   44,   47,
      247,  247,  247,   44,  247,  247,  247,  227,   44,  247,
      232,  247,  247,  228,   44,  247,  247,  229,   47,  230,
      247,   47,  247,  247,   47,   44,   44,   89,   89,   89,
       44,   44,   89,   89,   89,  232,  247,   47,   47,  247,
       47,   47,  247,  247,  233,   47,   47,  247,  234,   47,

      235,  247,  247,   47,  247,  247,  247,   44,  247,  247,
      247,  247,   44,   47,   47,  247,   47,   47,  247,  233,
       47,   47,  247,  234,   47,  235,  247,  247,   47,   44,
       44,   89,   89,   89,   44,   44,   89,   89,   89,   44,
       44,   89,   89,   89,   44,   44,   89,   89,   89,  247,
      247,  247,  236,   47,   47,  247,  238,  247,  247,  247,
       47,   44,  237,   47,  247,   47,   44,  242,   47,  247,
      247,   44,   47,  247,  247,  247,   44,  236,  247,   47,
       47,  247,  238,  247,  247,   47,  247,  237,   47,  247,
      247,   47,  242,  247,   47,  247,  247,   47,   44,   44,

       89,   89,   89,   44,   44,   89,   89,   89,   47,   44,
       44,   89,   89,   89,  240,  247,  247,  247,  241,  247,
      239,   44,   44,   89,   89,   89,  247,   47,  247,  247,
       44,  247,  247,  247,   47,   44,  247,  247,  247,  247,
      240,   44,  247,  241,  247,  239,   44,   44,   89,   89,
       89,  247,   47,   44,   44,   44,   89,   89,   89,   47,
      247,   47,  247,  247,  243,  247,  247,  247,   47,  247,
       47,  247,   47,  247,   47,  247,  247,  247,   44,   44,
       44,   89,   89,   89,  247,   47,   44,   47,  247,  243,
      244,  247,  247,   47,  247,   47,  247,   47,  247,   47,

       44,   44,   89,   89,   89,  247,   44,   44,   89,   89,
       89,   44,  247,  247,  247,  247,  244,  246,  247,   44,
       44,   89,   89,   89,  247,  245,  247,  247,  247,  247,
      247,  247,   44,  247,  247,  247,  247,  247,   44,  247,
      247,  247,  247,  246,  247,  247,  247,  247,  247,  247,
      245,   44,   38,   38,   38,   40,   40,   40,   47,   47,
       90,   90,    3,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247
    } ;

static const flex_int16_t yy_chk[2630] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   13,   13,   13,   14,
       14,   14,   14,   14,   15,   15,   15,   15,   15,   16,
       16,   16,   16,   16,  250,   40,   15,   38,    9,    8,
        3,   16,   44,   44,   44,   44,   44,    0,    0,   22,

       22,   14,    0,   22,    0,    0,   15,   22,    0,    0,
        0,   16,   15,    0,    0,    0,    0,   16,   19,   19,
       19,   19,   19,    0,   44,   22,   22,   23,   19,   22,
       23,    0,   22,    0,   23,    0,   19,    0,   45,   45,
       45,   45,   45,    0,   23,    0,    0,    0,    0,    0,
       19,    0,    0,   23,   19,    0,   23,    0,   85,   23,
        0,   19,   20,   20,   20,   20,   20,   85,    0,   23,
       45,   85,   26,   28,   20,   26,   28,   20,    0,   26,
       28,   20,    0,    0,   85,    0,   25,    0,   37,   25,
        0,   37,   85,   25,   20,   37,   85,   25,   26,   28,

       20,   26,   28,   20,   26,   28,   20,   21,   21,   21,
       21,   21,   25,    0,   37,   25,   29,   37,   25,   29,
       37,   21,   25,   29,    0,   29,    0,    0,   21,   42,
        0,    0,   42,    0,    0,    0,   42,    0,    0,   21,
        0,    0,   29,    0,   31,   29,    0,   21,   29,   31,
       29,    0,   31,   21,   24,   42,   31,   24,   42,   24,
        0,   42,   24,    0,    0,    0,   24,    0,    0,    0,
       31,   24,    0,   24,    0,   31,    0,    0,   31,    0,
       24,   31,    0,   24,    0,   24,   34,    0,   24,    0,
       34,   24,    0,   34,    0,    0,   24,   34,   24,   27,

       43,   27,    0,   43,   27,   51,    0,   43,   27,   27,
        0,    0,   34,    0,    0,   51,   34,    0,   27,   34,
        0,    0,   34,    0,   51,   27,   43,   27,    0,   43,
       27,   51,   43,   27,   27,   46,   46,   46,   46,   46,
       51,    0,    0,   27,   30,    0,    0,    0,   30,   51,
        0,   30,    0,   30,    0,   30,    0,   30,   47,   47,
       47,   47,   47,    0,    0,    0,   53,   46,    0,    0,
       30,    0,    0,    0,   30,    0,   53,   30,   30,    0,
       30,    0,   30,   32,    0,   53,   56,    0,   32,   56,
       47,   32,   53,   56,    0,   32,   50,   50,   50,   50,

       50,   53,    0,    0,   32,    0,    0,    0,    0,   32,
       53,    0,   56,    0,   32,   56,    0,   32,   56,    0,
       32,    0,    0,   48,   48,   48,   48,   48,   50,   32,
       33,   33,    0,   62,   33,    0,   62,    0,   33,    0,
       62,    0,    0,    0,    0,   33,    0,   48,    0,   49,
       49,   49,   49,   49,    0,   48,   33,   33,   52,   62,
       33,    0,   62,   33,    0,   62,   52,    0,   52,   57,
       33,   35,   48,   49,   35,    0,    0,   52,   35,   57,
        0,   49,   35,    0,   52,    0,   54,    0,   57,   35,
        0,   52,    0,   52,    0,   57,   54,   35,   49,    0,

       35,   54,   52,   35,   57,   54,    0,   35,    0,    0,
        0,    0,   54,   57,   35,   36,    0,    0,   36,    0,
        0,   54,    0,    0,    0,   36,   54,    0,    0,   36,
       54,    0,    0,    0,   36,   55,   55,   55,   55,   55,
        0,   36,   61,   58,   36,   60,   60,   77,    0,    0,
       36,   58,   61,   58,   36,   60,   61,   77,    0,   36,
        0,   61,   58,    0,   60,    0,   77,   55,   61,   58,
        0,   60,   60,   77,    0,    0,   58,   61,   58,    0,
       60,   61,   77,    0,    0,    0,   61,   58,   59,   60,
       63,   77,   64,   63,    0,   64,    0,   63,   59,   64,

        0,   59,   59,    0,    0,   64,    0,   59,   65,    0,
        0,   65,    0,    0,   59,   65,   63,    0,   64,   63,
        0,   64,   63,   59,   64,    0,   59,   59,    0,    0,
       64,    0,   59,    0,   65,   66,   67,   65,   66,   67,
       65,   66,   66,   67,    0,    0,   67,   68,   68,   68,
       68,   68,   69,    0,    0,   69,    0,    0,    0,   69,
        0,   66,   67,    0,   66,   67,   66,   66,   67,   70,
        0,   67,   70,   81,    0,    0,   70,    0,   69,   68,
        0,   69,    0,   81,   69,    0,   72,   75,    0,   72,
       75,    0,   81,   72,   75,   70,    0,   72,   70,   81,

        0,   70,   71,   71,   86,   71,    0,   86,   81,   71,
        0,   86,   72,   75,   71,   72,   75,   81,   72,   75,
        0,    0,   72,    0,    0,    0,    0,    0,   71,   71,
       86,   71,    0,   86,   71,    0,   86,    0,    0,   71,
       73,   74,   73,   73,   74,   73,    0,    0,   74,   73,
       76,    0,    0,   76,    0,   74,   73,   76,    0,    0,
        0,    0,    0,   76,    0,    0,   73,   74,   73,   73,
       74,   73,    0,   74,   73,    0,   76,    0,    0,   76,
       74,   73,   76,    0,    0,    0,   80,   82,   76,   78,
       78,   79,    0,   79,   79,    0,   80,   82,    0,    0,

       78,   80,   78,    0,    0,   80,   82,   79,   82,   78,
        0,   88,   80,   82,   88,   78,   78,   79,   88,   79,
       79,   80,   82,    0,    0,   78,   80,   78,   83,   83,
       80,   82,   79,   82,   78,    0,    0,   88,   83,   84,
       88,   87,    0,   88,   87,    0,    0,   83,   87,   84,
        0,   84,   87,    0,   83,   83,    0,    0,   84,    0,
        0,    0,    0,   83,    0,   84,    0,   87,   91,    0,
       87,   91,   83,   87,   84,   91,   84,   87,   89,   89,
       89,   89,   89,   84,   90,   90,   90,   90,   90,   92,
        0,    0,   92,    0,   91,    0,   92,   91,   93,   94,

       91,   93,    0,    0,    0,   93,    0,    0,   94,  117,
       89,    0,   94,    0,    0,   92,   90,    0,   92,  117,
        0,   92,   95,   95,   93,   94,    0,   93,  117,    0,
       93,    0,   95,   94,    0,  117,   95,   94,    0,    0,
        0,   97,   98,    0,  117,    0,    0,    0,   95,   95,
       97,   98,    0,  117,   97,   98,    0,   95,    0,   98,
        0,   95,   96,   96,   96,   96,   96,   97,   98,   96,
       96,    0,   96,  120,    0,   97,   98,   96,   99,   97,
       98,   99,    0,  120,   98,    0,    0,   99,    0,    0,
        0,   99,  120,    0,   96,   96,   96,  100,   96,  120,

      100,    0,  101,   96,   99,    0,  100,   99,  120,    0,
      100,  101,   99,    0,    0,  101,   99,  120,    0,    0,
      102,  102,    0,  100,    0,  103,  100,    0,  101,  102,
        0,  100,    0,  102,  103,  100,  101,    0,  103,  104,
      101,    0,  103,    0,  105,    0,  102,  102,  104,    0,
        0,  103,  104,  105,  102,  104,    0,  105,  102,  103,
        0,    0,  106,  103,    0,  104,    0,  103,    0,    0,
      105,  106,  106,  104,    0,  106,  107,  104,  105,    0,
      104,    0,  105,    0,    0,  107,    0,    0,  106,  107,
      108,  108,  108,  108,  108,    0,  106,  106,    0,    0,

      106,    0,  107,  109,  109,  109,  109,  109,  110,    0,
      107,  111,    0,    0,  107,  110,    0,  110,    0,    0,
      111,  110,  108,    0,  111,    0,    0,  111,  109,  113,
      112,    0,  113,    0,  110,  109,  113,  111,    0,  112,
        0,  110,  110,  112,    0,  111,  110,  114,    0,  111,
      114,    0,  111,  109,  114,  113,  112,    0,  113,  114,
      115,  113,  116,  115,  112,  116,    0,  115,  112,  116,
        0,  115,    0,  114,  116,    0,  114,    0,    0,  114,
        0,    0,    0,  119,  114,    0,  115,  119,  116,  115,
        0,  116,  115,  119,  116,  121,  115,  118,  118,  116,

        0,    0,  119,    0,  121,    0,    0,  118,  121,  119,
        0,    0,    0,  119,    0,    0,  118,  122,  119,    0,
        0,  121,    0,  118,  118,    0,  122,  119,  123,  121,
      122,  123,  118,  121,    0,  123,    0,  124,    0,    0,
      124,  118,    0,  122,  124,    0,  125,    0,  124,  125,
        0,  122,    0,  125,  123,  122,  126,  123,  125,    0,
      123,  126,    0,  124,  126,    0,  124,    0,  126,  124,
        0,    0,  125,  124,    0,  125,  127,  127,  125,    0,
      127,    0,  126,  125,  127,  140,    0,  126,  128,  128,
      126,    0,  128,  126,    0,  140,  128,  129,  129,  132,

        0,  129,  127,  127,  140,  129,  127,    0,  132,  127,
      130,  140,  132,  130,  128,  128,    0,  130,  128,  131,
      140,  128,  131,  129,  129,  132,  131,  129,    0,  140,
      129,    0,  131,  132,  133,    0,  130,  132,    0,  130,
      134,  134,  130,  133,    0,  131,    0,  133,  131,  134,
        0,  131,    0,  134,    0,    0,    0,  131,    0,    0,
      133,    0,  135,  135,    0,    0,  134,  134,  133,    0,
        0,  135,  133,    0,  134,  135,    0,    0,  134,  136,
      136,  136,  136,  136,    0,    0,    0,    0,  135,  135,
      137,  137,  137,  137,  137,    0,  135,    0,    0,    0,

      135,    0,  136,  138,  138,  138,  138,  138,  137,    0,
        0,  136,    0,    0,  138,  141,  139,  139,  139,  139,
      139,    0,  137,    0,    0,  141,    0,  136,  142,    0,
        0,  143,  143,  137,  141,  138,  139,    0,  142,    0,
      138,  141,  143,  142,    0,  144,    0,  142,  139,    0,
      141,  143,    0,    0,  142,  144,  145,  143,  143,  141,
      146,  139,    0,  142,  144,    0,  145,  143,  142,    0,
      146,  144,  142,    0,    0,  145,  143,    0,    0,  146,
      144,  147,  145,  148,    0,    0,  146,  150,    0,  144,
      147,  145,  148,    0,  147,  146,  148,  150,  149,    0,

      145,  149,    0,    0,  146,  149,  150,  147,    0,  148,
      151,    0,    0,  150,    0,  147,    0,  148,  152,  147,
      151,  148,  150,    0,  149,    0,  151,  149,  152,  151,
      149,  150,    0,    0,    0,  213,  151,  152,  213,  154,
      155,    0,  213,    0,  152,  151,    0,  154,    0,  154,
      155,  151,    0,  152,  151,    0,    0,    0,  154,  155,
        0,  213,  152,  153,  213,  154,  155,  213,  156,    0,
        0,    0,  154,  153,  154,  155,  153,  153,  156,    0,
      156,    0,  153,  154,  155,  158,    0,  156,    0,  153,
        0,    0,    0,    0,  156,  158,  157,    0,  153,    0,

      158,  153,  153,  156,  158,  156,  157,  153,    0,  157,
        0,  158,  156,  159,    0,  157,  160,    0,    0,    0,
      158,    0,  157,  159,    0,  158,  160,  161,    0,  158,
        0,  157,  159,  162,  157,  160,    0,  161,    0,  159,
      157,    0,  160,  162,  161,    0,  161,  162,  159,    0,
        0,  160,  162,  161,  163,    0,    0,  159,    0,  162,
      160,    0,  161,    0,  163,    0,  163,    0,  162,  161,
        0,  161,  162,  163,  164,  165,  166,  162,    0,    0,
      163,    0,    0,    0,  164,  165,  166,  164,    0,  163,
        0,  163,    0,  164,  165,  166,    0,    0,  163,    0,

      164,  165,  166,  167,  167,  167,  167,  167,    0,  164,
      165,  166,  164,  168,  168,  168,  168,  168,  164,  165,
      166,  169,  169,  169,  169,  169,  170,  170,  170,  170,
      170,    0,    0,  172,    0,  167,  171,  171,  171,  171,
      171,    0,  172,  171,    0,  168,  172,  173,  173,  173,
      173,  173,  170,  169,    0,  173,    0,  177,  170,  172,
        0,  174,  174,  174,  174,  174,  177,  172,  171,  171,
      177,  172,  175,  175,  175,  175,  175,  170,    0,  173,
        0,  173,  174,  177,  176,  176,  176,  176,  176,  178,
        0,  177,  178,  174,    0,  177,    0,  175,  178,  180,

      179,    0,  178,    0,  175,  176,    0,  174,  180,  179,
        0,    0,  180,  179,    0,  178,  176,  179,  178,    0,
        0,  220,  175,  178,  220,  180,  179,  178,  220,    0,
      176,  181,  181,  180,  179,  182,    0,  180,  179,    0,
        0,  181,  179,    0,  182,  181,  183,  220,  182,    0,
      220,  184,    0,  220,    0,  183,    0,  181,  181,  183,
      184,  182,    0,  183,  184,  185,  181,    0,    0,  182,
      181,    0,  183,  182,  185,    0,    0,  184,  185,    0,
      183,  187,    0,  186,  183,  184,  186,    0,  183,  184,
      187,  185,  186,    0,  187,    0,  186,  188,    0,  185,

        0,    0,    0,  185,    0,    0,  188,  187,    0,  186,
      188,  189,  186,  190,    0,  187,  190,  186,    0,  187,
      189,  186,  190,  188,  189,    0,  190,  191,    0,    0,
        0,  188,    0,    0,    0,  188,  191,  189,    0,  190,
      191,  192,  190,  193,    0,  189,    0,  190,    0,  189,
      192,  190,  193,  191,  192,    0,  193,    0,    0,    0,
        0,  191,    0,    0,    0,  191,    0,  192,    0,  193,
        0,    0,    0,    0,    0,  192,    0,  193,  195,  192,
        0,  193,  194,  194,  194,  194,  194,    0,  195,  197,
      196,  194,    0,    0,  194,    0,    0,  195,    0,  197,

      196,    0,  197,    0,  195,  196,    0,    0,  197,  196,
        0,    0,    0,  195,  194,  197,  196,  194,    0,    0,
      194,    0,  195,    0,  197,  196,    0,  197,    0,    0,
      196,    0,    0,  197,  196,  198,  198,  198,  198,  198,
      199,  199,  199,  199,  199,  198,    0,    0,    0,  199,
      200,  200,  200,  200,  200,  201,  201,  201,  201,  201,
      200,    0,    0,    0,  202,  201,    0,  198,  203,    0,
        0,  198,  199,    0,  202,  199,    0,  203,    0,  204,
        0,  203,  200,  202,  205,    0,  200,  201,  204,  204,
      202,  201,  204,  205,  203,    0,    0,  205,  206,  202,

        0,    0,  203,  207,    0,  204,  203,  206,  202,    0,
      205,  206,  207,  204,  204,    0,  207,  204,  205,    0,
        0,    0,  205,    0,  206,  208,  209,    0,    0,  207,
        0,    0,  206,    0,  208,  209,  206,  207,  208,  209,
      208,  207,    0,    0,    0,  210,  210,  210,  210,  210,
        0,  208,  209,  211,  211,  211,  211,  211,  212,  208,
      209,    0,    0,  208,  209,  208,  210,  212,  211,  219,
        0,  212,  219,    0,    0,  212,  219,  210,  214,    0,
      219,    0,    0,  214,  212,  211,  214,    0,    0,    0,
      214,  210,  212,    0,  211,  219,  212,    0,  219,    0,

      212,  219,    0,    0,  214,  219,    0,    0,    0,  214,
        0,    0,  214,    0,    0,  214,  215,  215,  215,  215,
      215,  216,  216,  216,  216,  216,  217,  217,  217,  217,
      217,  215,  218,  218,  218,  218,  218,    0,  216,    0,
        0,  217,  221,  218,    0,  221,    0,    0,  215,  221,
        0,    0,    0,  216,    0,    0,    0,  215,  217,    0,
      221,    0,    0,  216,  218,    0,    0,  217,  221,  218,
        0,  221,    0,    0,  221,  222,  222,  222,  222,  222,
      223,  223,  223,  223,  223,  221,    0,  225,  224,    0,
      226,  224,    0,    0,  222,  224,  225,    0,  223,  226,

      225,    0,    0,  226,    0,    0,    0,  222,    0,    0,
        0,    0,  223,  225,  224,    0,  226,  224,    0,  222,
      224,  225,    0,  223,  226,  225,    0,    0,  226,  227,
      227,  227,  227,  227,  228,  228,  228,  228,  228,  229,
      229,  229,  229,  229,  230,  230,  230,  230,  230,    0,
        0,    0,  227,  231,  238,    0,  231,    0,    0,    0,
      231,  227,  229,  238,    0,  232,  228,  238,  232,    0,
        0,  229,  232,    0,    0,    0,  230,  227,    0,  231,
      238,    0,  231,    0,    0,  231,    0,  229,  238,    0,
        0,  232,  238,    0,  232,    0,    0,  232,  233,  233,

      233,  233,  233,  234,  234,  234,  234,  234,  235,  236,
      236,  236,  236,  236,  234,    0,    0,    0,  235,    0,
      233,  237,  237,  237,  237,  237,    0,  235,    0,    0,
      233,    0,    0,    0,  235,  234,    0,    0,    0,    0,
      234,  236,    0,  235,    0,  233,  239,  239,  239,  239,
      239,    0,  235,  237,  240,  240,  240,  240,  240,  241,
        0,  242,    0,    0,  239,    0,    0,    0,  241,    0,
      242,    0,  241,    0,  242,    0,    0,    0,  239,  243,
      243,  243,  243,  243,    0,  241,  240,  242,    0,  239,
      243,    0,    0,  241,    0,  242,    0,  241,    0,  242,

      244,  244,  244,  244,  244,    0,  245,  245,  245,  245,
      245,  243,    0,    0,    0,    0,  243,  245,    0,  246,
      246,  246,  246,  246,    0,  244,    0,    0,    0,    0,
        0,    0,  244,    0,    0,    0,    0,    0,  245,    0,
        0,    0,    0,  245,    0,    0,    0,    0,    0,    0,
      244,  246,  248,  248,  248,  249,  249,  249,  251,  251,
      252,  252,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[79] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 4 "lexico.l"
#include <cstdlib>
#include "parser.h"
#include "command.h"
#include <stdio.h>
#include <iostream>
#include <list>

int yylex();
void yyerror(const char *s);
int linea=0; // Para contar lineas
int columna = 1; // para las columnas
int anterior = 0;
std::list<Command*> listCommand;
#line 1148 "scanner.cpp"
#line 1149 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 33 "lexico.l"

#line 1366 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 248 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2563 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "lexico.l"

	YY_BREAK

case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 36 "lexico.l"
{linea++;columna = 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return numero;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 38 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return cadena;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkdisk;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return psize;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pcont;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfit;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return punit;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ppath;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prmdisk;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfdisk;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ptype;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pallocation;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pdetele;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pname;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return padd;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmount;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return punmount;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkfs;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return plogin;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pusr;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ppwd;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return plogout;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkgrp;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prmgrp;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkusr;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prmusr;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pgrp;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pchmod;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkfile;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkdir;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pr;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pugo;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pid;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prep;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pexec;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pb;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pk;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pm;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pc;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pix;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbf;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pff;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfs;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return p2fs;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return p3fs;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pwf;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pp;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pe;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pl;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfast;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfull;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pruta;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ploss;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return precovery;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmbr;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pdisk;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbm_arbdir;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbm_detdir;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbm_inode;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbm_block;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbitacora;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pdirectorio;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ptree_file;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return psb;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ptree_complete;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return id;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return igual;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return guion; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return mayorQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ampersand; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 107 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return porcentaje; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 108 "lexico.l"
{
                    strcpy(yylval.TEXT, yytext); columna=26;
                }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 111 "lexico.l"
{ columna++; }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 112 "lexico.l"
{linea++; columna = 0; anterior = 0;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 "lexico.l"
{
                    columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);
/*                    errorT *nuevoE = new errorT("Lexico",yytext,linea, columna);
*/

                    std::cout <<yytext <<" Error Lexico en la linea "<< linea << " Columna:"<< columna<<  std::endl;
                }
	YY_BREAK

case 78:
YY_RULE_SETUP
#line 121 "lexico.l"
ECHO;
	YY_BREAK
#line 1836 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 248 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 248 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 247);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "lexico.l"


