#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[170] =
    {   0,
        0,    0,   64,   62,   59,   61,   60,   62,   62,   58,
       57,   55,   62,    3,    3,    3,   54,   56,   53,   37,
       53,   53,   47,   53,   53,   53,   53,   38,   48,   39,
       53,   46,   32,   53,   53,   53,   53,    0,    4,    0,
        2,   53,   53,   53,   53,    3,   53,   53,   53,   53,
       53,   40,   53,   53,   53,   53,   53,   53,   53,   41,
       53,   42,   53,   53,   34,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       45,   53,   53,   43,   44,   16,   53,   53,   53,   53,
       53,   53,   53,    8,   53,   28,   53,   53,   51,   53,

       53,   53,   53,   53,   53,   53,   22,   35,   53,   53,
       53,   53,   53,   33,   53,   53,   21,   53,    7,   53,
       52,   36,   49,   53,   50,   53,   53,   53,   53,   53,
       19,   53,   53,   53,   15,   10,   53,   53,   53,    6,
       13,    9,   53,   29,   53,   12,   53,   20,   53,   31,
       53,   53,   24,   26,   17,   53,   25,   27,   53,   14,
       53,   23,    5,   30,   11,   53,    1,   18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    8,    1,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   12,   13,
       14,   12,   12,   12,   12,   12,   12,    1,    1,    1,
       15,   16,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       26,   33,   34,   35,   36,   26,   37,   38,   39,   40,
        1,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   26,   51,   52,   53,   54,
       55,   56,   26,   57,   58,   59,   60,   26,   61,   62,
       63,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   26,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   26,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   26,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    3,    3,    3,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        2,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[175] =
    {   0,
        0,    0,   89, 1671, 1671, 1671, 1671,   83,   84, 1671,
     1671, 1671,   53,   58,   63,   68, 1671, 1671,   81,  106,
      144,  190,  121,  231,  130,  138,  282,  178,  216,  327,
      196,  373,  425,  249,  272,  469,  211,   81, 1671,   81,
     1671,  293,  305,  318,  338,  350,  361,  346,  358,  373,
      375,  394,  440,  442,  461,  474,  491,  506,  508,  521,
      538,  523,  555,  568,  571,  587,  600,  609,  648,  649,
      646,  682,  690,  691,  706,  727,  739,  143,  780,  725,
      609,  445,  677,  759,  761,  795,  797,  814,  816,  833,
      856,  850,  856,  868,  885,  894,  897,  922,  903,  932,

      944,  956,  961,  973,  978,  999, 1007, 1012, 1029, 1041,
     1028, 1067, 1070, 1089, 1097, 1099, 1117, 1139, 1122, 1140,
     1158, 1161, 1175, 1180, 1190, 1197, 1202, 1219, 1228, 1236,
     1257, 1266, 1269, 1295, 1298, 1310, 1311, 1340, 1327, 1332,
     1353, 1369, 1370, 1385, 1408, 1386, 1429, 1427, 1430, 1446,
     1394, 1472, 1455, 1474, 1489, 1495, 1506, 1512, 1511, 1524,
     1543, 1545, 1558, 1560, 1575, 1587, 1590, 1602, 1671, 1660,
     1663,   80, 1665, 1667
    } ;

static const flex_int16_t yy_def[175] =
    {   0,
      169,    1,  169,  169,  169,  169,  169,  170,  171,  169,
      169,  169,  172,  173,  173,  173,  169,  169,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  170,  169,  171,
      169,  173,  173,  174,  173,  173,  173,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   69,   36,   36,   30,   30,   30,
       30,  174,  174,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   36,   36,   36,   36,   36,   30,   30,   30,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       30,   30,   30,   30,   30,   30,   30,   30,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,    0,  169,
      169,  169,  169,  169
    } ;

static const flex_int16_t yy_nxt[1736] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,    4,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   26,   28,   29,   30,   31,
       26,   32,   33,   34,   35,   36,   37,   26,   26,   26,
        4,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   26,   32,   33,   34,   35,   36,
       37,   26,   26,   26,   42,   42,   42,   44,   45,   46,
       46,   46,   44,   45,   46,   46,   46,   44,   45,   46,
       46,   46,   43,   41,   48,   39,   41,   39,  169,   49,
       44,   45,   50,   50,   50,  169,  169,  169,   44,  169,

       51,  169,  169,   44,  169,  169,  169,  169,   44,   48,
      169,  169,  169,  169,   49,   44,   45,   50,   50,   50,
      169,   44,  169,  169,  169,   51,  169,   52,  169,  169,
       44,   45,   50,   50,   50,  169,  169,  169,  169,   44,
       45,   50,   50,   50,  169,  169,   44,   44,   45,   50,
       50,   50,   52,   44,   45,   50,   50,   50,   57,  169,
       47,   44,   64,  169,  169,  169,  169,   53,  169,   47,
       44,  169,  169,  114,   54,  169,  169,  169,   44,  169,
      169,  169,   57,  169,   44,   47,   64,   44,   45,   50,
       50,   50,   53,   47,  169,  169,  169,  114,   54,   44,

       45,   50,   50,   50,  169,   44,   45,   50,   50,   50,
       55,  169,   71,  169,   56,  169,  169,  169,   44,  169,
       44,   45,   50,   50,   50,   44,   45,   50,   50,   50,
       44,  169,   81,  169,  169,   55,   44,   71,  169,   56,
       44,   45,   50,   50,   50,  169,   67,   58,  169,  169,
       59,   44,   60,  169,  169,   61,   44,   81,   44,   45,
       50,   50,   50,  169,   62,  169,   63,  169,  169,  169,
       67,   44,   58,   76,  169,   59,  169,   60,  169,  169,
       61,   44,   45,   50,   50,   50,  169,  169,   62,   44,
       63,   44,   45,   50,   50,   50,  169,  169,   76,  169,

      169,   65,   44,   45,   50,   50,   50,  169,  169,  169,
       77,   66,   44,  169,   44,   45,   50,   50,   50,  169,
      169,  169,   44,  169,  169,  169,   65,   44,   44,   82,
       82,   82,  169,   44,   77,   66,   44,   45,   50,   50,
       50,  169,  169,  169,   68,   44,  169,   44,   44,   50,
       50,   50,  169,   69,  169,  169,  169,   70,   44,   44,
       45,   46,   46,   46,  169,  169,  169,   44,   47,   68,
       44,   45,   50,   50,   50,   47,  169,   69,   44,   84,
       47,   70,   44,   45,   50,   50,   50,   47,  169,   72,
       44,   85,  169,   47,   86,   47,  169,   47,  169,   47,

      169,   44,   47,   84,   47,   47,   47,  169,   47,   73,
      169,   47,  169,   44,   72,   85,   47,  169,  169,   86,
       47,  169,   47,   47,  169,  169,   47,   47,   47,  169,
       47,  169,   47,   73,   44,   45,   50,   50,   50,  169,
      169,   47,  169,  169,  169,   74,  169,   47,  169,  169,
      169,   47,  169,   75,   44,   44,   82,   82,   82,  169,
      169,  169,   47,  169,   47,   44,  169,  169,   87,   47,
       74,   88,  169,   47,  169,   47,  169,   75,   44,   45,
       50,   50,   50,   47,  169,   44,  169,   47,   89,   47,
       47,   78,   87,   47,   47,   88,   47,   47,   79,   47,

      169,  169,   80,   47,  169,  169,  169,   90,   47,   44,
      169,   91,   89,   47,   47,  169,   78,  169,   47,  169,
       47,   47,   79,  169,   47,  169,   80,   47,   47,  169,
       47,   90,   93,  169,  169,   47,   91,   47,   47,   92,
      169,   47,  169,   47,   47,   47,  169,  169,   47,  169,
       47,  169,   47,   47,   47,   47,   47,   93,  169,   47,
       47,   47,  169,   92,  169,   47,  169,   47,   47,  169,
       47,   47,   94,  169,   47,  169,   47,   47,   47,  169,
       47,  169,   95,  169,   47,   47,  169,  169,   47,  169,
       47,   47,  169,   47,  169,   47,   94,   47,  169,   96,

       47,   47,   47,  169,   47,  169,   95,  169,   47,   47,
      169,   97,   47,  169,  169,   47,   47,  169,   47,  169,
       47,   47,   98,   96,   47,   47,   47,  169,   47,   47,
      169,   47,  169,   47,   47,   47,   97,  169,   47,   47,
       47,   99,   47,  169,   47,  169,  169,   98,  169,  169,
      169,   47,  169,   47,  169,  169,   47,   47,  169,   47,
      169,  169,   47,   47,  169,   99,   47,  100,   47,  101,
      102,   47,  169,  169,  105,   47,  169,   47,   47,   47,
      169,   47,   47,  103,  104,  169,   44,   44,   82,   82,
       82,  169,  100,   47,  101,  102,   47,  169,  105,   47,

      169,   47,   47,   47,   47,   47,   47,  103,  104,  107,
      169,   47,   47,   47,  169,   47,  106,   44,  169,   47,
       47,  169,  108,   47,   47,  109,  169,   47,  110,   47,
      169,  169,  169,  169,  107,   47,  169,   47,   47,   47,
      106,  111,   47,   47,   47,  169,  108,   47,   47,   47,
      109,   47,   47,  110,  169,   47,   47,  117,  169,  169,
       47,   47,  169,  169,  169,  111,  112,   47,   47,  169,
      113,  169,   47,  169,   47,   47,   47,  169,   47,   47,
       47,  117,  169,  169,   47,   47,   47,   47,  169,   47,
      112,   47,   47,  169,  113,  169,   47,   47,  169,  169,

      169,   47,  169,   47,  115,  169,   47,  169,  116,   47,
       47,   47,   47,   47,   47,   47,  169,  169,  169,  169,
      169,   47,   47,   47,  169,   47,  169,  118,  169,  115,
       47,   47,  116,   47,   47,  169,  120,   47,  169,   47,
       47,  169,   47,  169,   47,   47,   47,   47,  119,   47,
       47,  118,  169,  169,  169,  169,   47,  169,   47,  121,
      169,  120,  169,   47,   47,  169,   47,   47,   47,  169,
       47,  169,  119,   47,  122,   47,   47,  169,   47,  169,
       47,  169,   47,  121,  123,   47,   47,   47,  169,  124,
       47,  169,   47,  169,  169,  169,  169,   47,   47,  122,

       47,   47,  169,   47,   47,  169,   47,   47,  123,   47,
       47,  169,  125,  124,   47,   47,   47,  169,   47,   47,
       47,   47,  169,   47,  169,   47,   47,   47,  169,   47,
       47,  126,   47,   47,  169,  169,  125,  169,   47,   47,
      169,   47,   47,  169,   47,   47,  127,   47,   47,   47,
       47,   47,  128,   47,   47,  126,  129,   47,   47,  169,
      169,  169,   47,  169,   47,  169,   47,  169,  130,  169,
      169,  127,   47,   47,   47,  169,  128,  131,   47,  169,
      169,  129,   47,   47,  169,   47,   47,  169,  132,   47,
       47,   47,  169,  130,  133,   47,  169,   47,  135,  169,

       47,  131,  134,   47,  169,  169,   47,   47,   47,   47,
      169,   47,  132,   47,   47,  169,  169,  169,  133,  169,
       47,   47,  136,  135,  169,   47,  134,  169,   47,   47,
       47,   47,   47,  169,   47,   47,   47,  169,  169,  169,
       47,   47,  169,  169,  169,   47,   47,  136,  169,  169,
       47,   47,   47,  137,   47,  169,   47,   47,   47,   47,
       47,  139,   47,   47,   47,   47,  169,  169,  169,   47,
       47,  169,  169,  138,   47,   47,   47,  169,  137,  169,
      169,   47,   47,  169,  169,  139,   47,  140,   47,   47,
      141,  169,   47,  169,   47,  169,   47,  138,   47,   47,

       47,  169,  169,   47,  169,  169,  169,  169,  169,  169,
      169,   47,  140,  169,   47,  141,   47,   47,   47,   47,
       47,  169,   47,   47,   47,   47,   47,   47,  169,  143,
       47,  142,  169,  169,   47,  169,   47,  169,  169,   47,
      169,   47,   47,   47,   47,  169,   47,   47,   47,   47,
       47,  169,   47,  143,   47,  142,   47,   47,  144,   47,
      169,  169,  169,  169,   47,   47,   47,   47,  169,   47,
       47,   47,   47,  169,  145,   47,   47,  169,   47,  169,
      169,   47,   47,  144,   47,  169,  169,   47,   47,   47,
       47,   47,   47,   47,   47,  169,  169,   47,  145,  169,

       47,   47,  169,   47,  169,   47,  146,   47,   47,  169,
       47,   47,   47,  169,   47,   47,   47,   47,  169,  169,
       47,  147,   47,   47,   47,   47,  169,   47,  169,   47,
      146,  148,   47,  169,   47,   47,  169,  169,  169,   47,
       47,   47,  169,  169,   47,  169,  147,   47,   47,   47,
       47,   47,   47,  169,  149,  148,  169,   47,   47,   47,
      150,  151,  169,  152,  169,   47,   47,  169,  169,   47,
      169,  169,   47,  169,  169,   47,   47,  169,  149,   47,
      169,   47,  169,   47,  150,  151,   47,  152,   47,   47,
       47,   47,  169,   47,  169,   47,  169,  153,   47,   47,

      169,  154,   47,  169,   47,  169,  169,  169,  169,  169,
       47,  169,  169,   47,   47,  169,   47,   47,  169,   47,
       47,  153,   47,   47,   47,  154,   47,   47,   47,  155,
      169,   47,   47,   47,  169,  169,  169,  169,  169,   47,
       47,  169,   47,   47,  156,   47,  169,  169,   47,   47,
      169,   47,   47,  155,   47,   47,   47,   47,   47,  158,
       47,   47,   47,   47,   47,   47,  169,   47,  156,   47,
      169,  157,  169,   47,   47,   47,  169,  169,  169,   47,
       47,  169,   47,  158,   47,   47,   47,   47,  169,   47,
      169,   47,   47,   47,  169,  157,  169,   47,   47,   47,

       47,  169,   47,   47,  169,  159,   47,   47,   47,  169,
       47,   47,  169,  169,   47,   47,   47,   47,   47,   47,
      163,  169,   47,   47,   47,  169,   47,   47,  160,  159,
       47,  169,   47,   47,  169,  169,   47,   47,   47,   47,
      169,   47,   47,   47,  163,  161,  169,  169,   47,   47,
      169,   47,   47,  160,  169,   47,   47,  169,   47,   47,
       47,   47,   47,   47,  162,   47,  169,  169,   47,  169,
      161,  169,   47,  169,   47,   47,   47,   47,  169,   47,
       47,   47,   47,   47,   47,   47,   47,   47,  162,   47,
      169,   47,  164,   47,  169,  169,  169,   47,   47,   47,

       47,  169,   47,   47,   47,   47,   47,  169,  169,   47,
      169,  169,   47,  169,   47,   47,   47,  164,  169,   47,
      169,  165,   47,   47,   47,   47,   47,  169,   47,   47,
      169,   47,   47,   47,  169,  169,   47,   47,   47,   47,
      166,  169,   47,   47,   47,  165,   47,  169,   47,   47,
      169,  169,  169,   47,   47,  169,   47,   47,   47,  169,
       47,  169,   47,  169,  166,   47,   47,   47,   47,  169,
      167,   47,   47,  169,   47,  169,   47,   47,   47,  169,
       47,   47,   47,  169,  169,  169,  169,   47,  169,   47,
       47,   47,   47,   47,  167,  169,   47,   47,   47,  169,

       47,  169,   47,  169,   47,   47,  169,   47,   47,   47,
      169,   47,   47,   47,  169,   47,   47,   47,  169,   47,
       47,  168,   47,   47,   47,  169,  169,  169,   47,  169,
      169,   47,   47,  169,   47,   47,  169,   47,  169,  169,
       47,  169,  169,   47,   47,  168,  169,   47,  169,   47,
      169,  169,  169,  169,  169,   47,  169,  169,  169,   47,
       38,   38,   38,   40,   40,   40,   47,   47,   83,   83,
        3,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,

      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169
    } ;

static const flex_int16_t yy_chk[1736] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   13,   13,   13,   14,   14,   14,
       14,   14,   15,   15,   15,   15,   15,   16,   16,   16,
       16,   16,  172,   40,   15,   38,    9,    8,    3,   16,
       19,   19,   19,   19,   19,    0,    0,    0,   14,    0,

       19,    0,    0,   15,    0,    0,    0,    0,   16,   15,
        0,    0,    0,    0,   16,   20,   20,   20,   20,   20,
        0,   19,    0,    0,    0,   19,    0,   20,    0,    0,
       23,   23,   23,   23,   23,    0,    0,    0,    0,   25,
       25,   25,   25,   25,    0,    0,   20,   26,   26,   26,
       26,   26,   20,   21,   21,   21,   21,   21,   23,    0,
       78,   23,   25,    0,    0,    0,    0,   21,    0,   78,
       25,    0,    0,   78,   21,    0,    0,    0,   26,    0,
        0,    0,   23,    0,   21,   78,   25,   28,   28,   28,
       28,   28,   21,   78,    0,    0,    0,   78,   21,   22,

       22,   22,   22,   22,    0,   31,   31,   31,   31,   31,
       22,    0,   31,    0,   22,    0,    0,    0,   28,    0,
       37,   37,   37,   37,   37,   29,   29,   29,   29,   29,
       22,    0,   37,    0,    0,   22,   31,   31,    0,   22,
       24,   24,   24,   24,   24,    0,   29,   24,    0,    0,
       24,   37,   24,    0,    0,   24,   29,   37,   34,   34,
       34,   34,   34,    0,   24,    0,   24,    0,    0,    0,
       29,   24,   24,   34,    0,   24,    0,   24,    0,    0,
       24,   35,   35,   35,   35,   35,    0,    0,   24,   34,
       24,   27,   27,   27,   27,   27,    0,    0,   34,    0,

        0,   27,   42,   42,   42,   42,   42,    0,    0,    0,
       35,   27,   35,    0,   43,   43,   43,   43,   43,    0,
        0,    0,   27,    0,    0,    0,   27,   44,   44,   44,
       44,   44,    0,   42,   35,   27,   30,   30,   30,   30,
       30,    0,    0,    0,   30,   43,    0,   45,   45,   45,
       45,   45,    0,   30,    0,    0,    0,   30,   44,   46,
       46,   46,   46,   46,    0,    0,    0,   30,   48,   30,
       47,   47,   47,   47,   47,   48,    0,   30,   45,   48,
       49,   30,   32,   32,   32,   32,   32,   49,    0,   32,
       46,   49,    0,   48,   51,   50,    0,   51,    0,   48,

        0,   47,   50,   48,   51,   49,   50,    0,   51,   32,
        0,   49,    0,   32,   32,   49,   52,    0,    0,   51,
       50,    0,   51,   52,    0,    0,   50,   52,   51,    0,
       50,    0,   51,   32,   33,   33,   33,   33,   33,    0,
        0,   52,    0,    0,    0,   33,    0,   52,    0,    0,
        0,   52,    0,   33,   82,   82,   82,   82,   82,    0,
        0,    0,   53,    0,   54,   33,    0,    0,   53,   53,
       33,   54,    0,   53,    0,   54,    0,   33,   36,   36,
       36,   36,   36,   55,    0,   82,    0,   53,   55,   54,
       55,   36,   53,   53,   55,   54,   56,   53,   36,   54,

        0,    0,   36,   56,    0,    0,    0,   56,   55,   36,
        0,   57,   55,   57,   55,    0,   36,    0,   55,    0,
       57,   56,   36,    0,   57,    0,   36,   56,   58,    0,
       59,   56,   59,    0,    0,   58,   57,   59,   57,   58,
        0,   59,    0,   60,   57,   62,    0,    0,   57,    0,
       60,    0,   62,   58,   60,   59,   62,   59,    0,   58,
       61,   59,    0,   58,    0,   59,    0,   61,   60,    0,
       62,   61,   61,    0,   60,    0,   62,   63,   60,    0,
       62,    0,   63,    0,   63,   61,    0,    0,   63,    0,
       64,   61,    0,   65,    0,   61,   61,   64,    0,   64,

       65,   64,   63,    0,   65,    0,   63,    0,   63,   66,
        0,   66,   63,    0,    0,   64,   66,    0,   65,    0,
       66,   64,   67,   64,   65,   64,   81,    0,   65,   67,
        0,   68,    0,   67,   66,   81,   66,    0,   68,   81,
       66,   68,   68,    0,   66,    0,    0,   67,    0,    0,
        0,   81,    0,   67,    0,    0,   68,   67,    0,   81,
        0,    0,   68,   81,    0,   68,   68,   69,   71,   69,
       69,   70,    0,    0,   71,   71,    0,   69,   70,   71,
        0,   69,   70,   69,   70,    0,   83,   83,   83,   83,
       83,    0,   69,   71,   69,   69,   70,    0,   71,   71,

        0,   69,   70,   71,   72,   69,   70,   69,   70,   73,
        0,   72,   73,   74,    0,   72,   72,   83,    0,   73,
       74,    0,   74,   73,   74,   75,    0,   75,   75,   72,
        0,    0,    0,    0,   73,   72,    0,   73,   74,   72,
       72,   75,   80,   73,   74,    0,   74,   73,   74,   76,
       75,   80,   75,   75,    0,   80,   76,   80,    0,    0,
       76,   77,    0,    0,    0,   75,   76,   80,   77,    0,
       77,    0,   77,    0,   76,   80,   84,    0,   85,   80,
       76,   80,    0,    0,   76,   84,   77,   85,    0,   84,
       76,   85,   77,    0,   77,    0,   77,   79,    0,    0,

        0,   84,    0,   85,   79,    0,   79,    0,   79,   84,
       79,   85,   86,   84,   87,   85,    0,    0,    0,    0,
        0,   86,   79,   87,    0,   86,    0,   87,    0,   79,
       79,   88,   79,   89,   79,    0,   89,   86,    0,   87,
       88,    0,   89,    0,   88,   86,   89,   87,   88,   86,
       90,   87,    0,    0,    0,    0,   88,    0,   89,   90,
        0,   89,    0,   90,   88,    0,   89,   92,   88,    0,
       89,    0,   88,   91,   91,   90,   92,    0,   93,    0,
       92,    0,   91,   90,   92,   93,   91,   90,    0,   93,
       94,    0,   92,    0,    0,    0,    0,   94,   91,   91,

       92,   94,    0,   93,   92,    0,   91,   95,   92,   93,
       91,    0,   95,   93,   95,   94,   96,    0,   95,   97,
       99,   94,    0,   96,    0,   94,   97,   96,    0,   99,
       97,   97,   95,   99,    0,    0,   95,    0,   95,   98,
        0,   96,   95,    0,   97,   99,   98,   96,   98,  100,
       97,   96,   98,   99,   97,   97,  100,   99,  100,    0,
        0,    0,  100,    0,   98,    0,  101,    0,  101,    0,
        0,   98,   98,  101,  100,    0,   98,  101,  102,    0,
        0,  100,  100,  103,    0,  102,  100,    0,  102,  102,
      103,  101,    0,  101,  103,  104,    0,  101,  105,    0,

      105,  101,  104,  102,    0,    0,  104,  105,  103,  102,
        0,  105,  102,  102,  103,    0,    0,    0,  103,    0,
      104,  106,  106,  105,    0,  105,  104,    0,  106,  107,
      104,  105,  106,    0,  108,  105,  107,    0,    0,    0,
      107,  108,    0,    0,    0,  108,  106,  106,    0,    0,
      111,  109,  106,  109,  107,    0,  106,  111,  109,  108,
      107,  111,  109,  110,  107,  108,    0,    0,    0,  108,
      110,    0,    0,  110,  110,  111,  109,    0,  109,    0,
        0,  111,  109,    0,    0,  111,  109,  112,  110,  112,
      113,    0,  113,    0,  110,    0,  112,  110,  110,  113,

      112,    0,    0,  113,    0,    0,    0,    0,    0,    0,
        0,  114,  112,    0,  112,  113,  116,  113,  114,  115,
      112,    0,  114,  113,  112,  116,  115,  113,    0,  116,
      115,  115,    0,    0,  117,    0,  114,    0,    0,  119,
        0,  116,  114,  117,  115,    0,  114,  117,  119,  116,
      115,    0,  119,  116,  115,  115,  118,  120,  118,  117,
        0,    0,    0,    0,  119,  118,  120,  117,    0,  118,
      120,  117,  119,    0,  120,  121,  119,    0,  122,    0,
        0,  118,  120,  118,  121,    0,    0,  122,  121,  118,
      120,  122,  123,  118,  120,    0,    0,  124,  120,    0,

      121,  123,    0,  122,    0,  123,  124,  125,  121,    0,
      124,  122,  121,    0,  126,  122,  125,  123,    0,    0,
      125,  126,  124,  126,  127,  123,    0,  126,    0,  123,
      124,  127,  125,    0,  124,  127,    0,    0,    0,  126,
      125,  128,    0,    0,  125,    0,  126,  126,  128,  127,
      129,  126,  128,    0,  128,  127,    0,  129,  130,  127,
      129,  129,    0,  130,    0,  130,  128,    0,    0,  130,
        0,    0,  128,    0,    0,  129,  128,    0,  128,  131,
        0,  129,    0,  130,  129,  129,  131,  130,  132,  130,
      131,  133,    0,  130,    0,  132,    0,  132,  133,  132,

        0,  133,  133,    0,  131,    0,    0,    0,    0,    0,
      131,    0,    0,  132,  131,    0,  133,  134,    0,  132,
      135,  132,  133,  132,  134,  133,  133,  135,  134,  134,
        0,  135,  136,  137,    0,    0,    0,    0,    0,  136,
      137,    0,  134,  136,  137,  135,    0,    0,  134,  139,
        0,  135,  134,  134,  140,  135,  139,  136,  137,  139,
      139,  140,  138,  136,  137,  140,    0,  136,  137,  138,
        0,  138,    0,  138,  139,  141,    0,    0,    0,  140,
      139,    0,  141,  139,  139,  140,  141,  138,    0,  140,
        0,  142,  143,  138,    0,  138,    0,  138,  142,  143,

      141,    0,  142,  143,    0,  143,  141,  144,  146,    0,
      141,  151,    0,    0,  144,  146,  142,  143,  144,  146,
      151,    0,  142,  143,  151,    0,  142,  143,  145,  143,
      145,    0,  144,  146,    0,    0,  151,  145,  144,  146,
        0,  145,  144,  146,  151,  147,    0,    0,  151,  148,
        0,  147,  149,  145,    0,  145,  148,    0,  147,  149,
      148,  145,  147,  149,  149,  145,    0,    0,  150,    0,
      147,    0,  153,    0,  148,  150,  147,  149,    0,  150,
      148,  153,  147,  149,  148,  153,  147,  149,  149,  152,
        0,  154,  152,  150,    0,    0,    0,  153,  152,  150,

      154,    0,  152,  150,  154,  153,  155,    0,    0,  153,
        0,    0,  156,    0,  152,  155,  154,  152,    0,  155,
        0,  156,  152,  157,  154,  156,  152,    0,  154,  158,
        0,  155,  157,  159,    0,    0,  157,  156,  158,  155,
      159,    0,  158,  155,  159,  156,  160,    0,  157,  156,
        0,    0,    0,  160,  158,    0,  157,  160,  159,    0,
      157,    0,  158,    0,  159,  161,  158,  162,  159,    0,
      161,  160,  161,    0,  162,    0,  161,  160,  162,    0,
      163,  160,  164,    0,    0,    0,    0,  163,    0,  164,
      161,  163,  162,  164,  161,    0,  161,  165,  162,    0,

      161,    0,  162,    0,  165,  163,    0,  164,  165,  166,
        0,  163,  167,  164,    0,  163,  166,  164,    0,  167,
      166,  166,  165,  167,  168,    0,    0,    0,  165,    0,
        0,  168,  165,    0,  166,  168,    0,  167,    0,    0,
      166,    0,    0,  167,  166,  166,    0,  167,    0,  168,
        0,    0,    0,    0,    0,  168,    0,    0,    0,  168,
      170,  170,  170,  171,  171,  171,  173,  173,  174,  174,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,

      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[64] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 4 "lexico.l"
#include <cstdlib>
#include "parser.h"
#include "command.h"
#include <stdio.h>
#include <iostream>
#include <list>

int yylex();
void yyerror(const char *s);
int linea=0; // Para contar lineas
int columna = 1; // para las columnas
int anterior = 0;
std::list<Command*> listCommand;
#line 925 "scanner.cpp"
#line 926 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 33 "lexico.l"

#line 1143 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 170 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1671 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "lexico.l"

	YY_BREAK

case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 36 "lexico.l"
{linea++;columna = 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return numero;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 38 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return cadena;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkdisk;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return psize;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pcont;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfit;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return punit;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ppath;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prmdisk;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfdisk;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ptype;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pdetele;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pname;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return padd;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmount;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return punmount;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkfs;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return plogin;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pusr;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ppwd;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return plogout;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkgrp;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prmgrp;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkusr;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prmusr;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pgrp;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pchmod;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkfile;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmkdir;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pr;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pugo;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pid;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return prep;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pexec;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pb;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pk;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pm;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pbf;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pff;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfs;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return p2fs;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return p3fs;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pwf;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pp;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pe;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pl;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfast;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pfull;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pmbr;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return pdisk;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return id;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "lexico.l"
{ columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return igual;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return guion; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return mayorQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return ampersand; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "lexico.l"
{   columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext); return porcentaje; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "lexico.l"
{
                    strcpy(yylval.TEXT, yytext); columna=26;
                }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 96 "lexico.l"
{ columna++; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 97 "lexico.l"
{linea++; columna = 0; anterior = 0;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 98 "lexico.l"
{
                    columna=columna+ anterior;  anterior = strlen(yytext);strcpy(yylval.TEXT, yytext);
/*                    errorT *nuevoE = new errorT("Lexico",yytext,linea, columna);
*/

                    std::cout <<yytext <<" Error Lexico en la linea "<< linea << " Columna:"<< columna<<  std::endl;
                }
	YY_BREAK

case 63:
YY_RULE_SETUP
#line 106 "lexico.l"
ECHO;
	YY_BREAK
#line 1538 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 170 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 170 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 169);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "lexico.l"


